### ISSUE TITLE
water heat capacity

### ISSUE THREAD

**Issue by lqxyz** [brian-rose/ClimateModeling_courseware#2]
Hello, I think the heat capacity for water (`c_w`) in `Lecture14 -- Heat transport.ipynb` should be `4.2e3 J/kg/K`, not `4.2 J/kg/K`, right?

**Comment by brian-rose** [comment]
Yes! Thanks for pointing that out. That particular section of the notes has never been finished. But I will fix that error.

**Comment by brian-rose** [comment]
Fixed in f5e277350cc0fb76301a3a7abd7cac4a5d58b1d7
