### ISSUE TITLE
issue with unknown character in latex equations

### ISSUE THREAD

**Issue by adriantompkins** [brian-rose/ClimateModeling_courseware#6]
Some of the latex equations in lecture 19 are messed up since the last commit with unknown characters

**Comment by brian-rose** [comment]
I'm not seeing that! Can you point me to something more specific?

**Comment by adriantompkins** [comment]
hi Brian

when I view the lectures on git hub lecture 16 section 2 onwards has the 
symbol messed up for latitude...

https://github.com/brian-rose/ClimateModeling_courseware/blob/master/Lectures/Lecture16%20--%20Diffusive%20energy%20balance%20model.ipynb

Both on chrome on mac and on firefox on a linux box....

my students really liked playing with the EBM in lecture 19 by the way.

best wishes, adrian

**Comment by brian-rose** [comment]
I see.

The GitHub viewer for *.ipynb files is not really full-featured. For viewing only (as opposed to interactive use), you'll have better results using https://nbviewer.jupyter.org.

Lecture 16 on nbviewer seems to have all the latex symbols properly rendered:
https://nbviewer.jupyter.org/github/brian-rose/ClimateModeling_courseware/blob/master/Lectures/Lecture16%20--%20Diffusive%20energy%20balance%20model.ipynb

**Comment by brian-rose** [comment]
@adriantompkins I'm closing this issue under the assumption that my comment above was helpful. Please re-open if you're still having problems with latex rendering.
