### ISSUE TITLE
Lecture 11 water vapor data

### ISSUE THREAD

**Issue by LyssaFreese** [brian-rose/ClimateModeling_courseware#7]
the water vapor database in lecture 11 is not working--it returns an "Error -3 while decompressing data: invalid stored block lengths"

**Comment by brian-rose** [comment]
The data servers we are running at UAlbany have been a bit temperamental lately. However I just tried running this notebook and it worked as expected. I suggest you try again!

If you encounter the same error, please let me know what version of xarray you are using. Thanks.

**Comment by LyssaFreese** [comment]
Thanks, Brian! It's working now so it might have just been down for a bit.
